apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
    - image: django-store
      context: src/store
    - image: django-store-nginx
      context: src/store
      docker:
        dockerfile: Dockerfile.nginx
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
  # kustomize: {}
  kubeContext: minikube # Default
